### ISSUE TITLE
For other app using...

### ISSUE THREAD

**Issue by kuan-hsu** [rizmut/libreoffice-style-sifr#14]
Thank you for your wonderful creations, your icons are very beautiful!

I would like to ask: Can I use your icons in my program besides LIBREOFFICE? Because I didn't find any part about License usage?

My program is freeBASIC's IDE: https://bitbucket.org/KuanHsu/poseidonfb/src/master/

**Comment by rizmut** [comment]
Hi the license is here

https://github.com/rizmut/libreoffice-style-sifr/blob/master/build/Sifr-IconSet/registration/license.txt

**Comment by kuan-hsu** [comment]
Thanks

**Comment by kuan-hsu** [comment]
Thanks
